/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    NewTodoInput: typeof import('./components/NewTodoInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoDetail: typeof import('./components/TodoDetail.vue')['default']
    TodoItem: typeof import('./components/TodoItem.vue')['default']
  }
}
